global:
  scrape_interval: 5s
  scrape_timeout: 5s
global: {evaluation_interval: 5s, scrape_interval: 5s}
scrape_configs:
- job_name: pushgateway
  static_configs:
  - targets: ['pushgateway:9091']
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']