alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
remote_write:
  - url: "http://influx:8086/api/v1/prom/write?db=prometheus"
global: {evaluation_interval: 5s, scrape_interval: 5s}
rule_files: [/opt/Monitoring/prometheus/rules/test.yaml]
scrape_configs:
- job_name: pushgateway
  static_configs:
  - targets: ['pushgateway:9091']
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
