{
 "title": "SP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "id",
    "query": "label_values({exported_job=\"vm\"},resource_id)"
   },
   { "name": "entity", "label": "entity", "query": "label_values(exported_job)" },
   {
    "name": "env",
    "label": "env",
    "query": "label_values({exported_job=\"vm\"},exported_instance)"
   }
  ]
 },
 "panels": [
  { "title": "SP_Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU USAGE (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cnt_cpu_perc{exported_job='containers'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MEMORY USAGE (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cnt_mem_perc{exported_job='containers'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RX NETWORK TRAFFIC (MB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cnt_net_rx_MB{exported_job='containers'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "SP_VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TX NETWORK TRAFFIC (MB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cnt_net_tx_MB{exported_job='containers'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU USAGE (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "repeat": "VMs",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_cpu_perc{exported_job=\"$entity\",resource_id=\"$id\"}",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_mem_perc{exported_job=\"$entity\",resource_id=\"$id\"}",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "DISK USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_disk_usage_perc{exported_job=\"$entity\",resource_id=\"$id\"}",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "RX NETWORK TRAFFIC (bps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_net_rx_bps{exported_job=\"$entity\",resource_id=\"$id\"}",
     "legendFormat": "{{inf}}"
    }
   ]
  },
  {
   "title": "TX NETWORK TRAFFIC (bps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_net_tx_bps{exported_job=\"$entity\",resource_id=\"$id\"}",
     "legendFormat": "{{inf}}"
    }
   ]
  }
 ]
}