FROM grafana/grafana:6.0.2 

USER root

ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_LOG_MODE=file

ADD ./datasources/ /etc/grafana/provisioning/datasources/
ADD ./dashboards/vnv/ /etc/grafana/provisioning/dashboards/
RUN ls -la /etc/grafana/provisioning/datasources/
RUN ls -la /etc/grafana/provisioning/dashboards/

EXPOSE 3000