{
 "title": "SP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "id",
    "query": "label_values({exported_job=\"vm\"},resource_id)"
   },
   { "name": "entity", "label": "entity", "query": "label_values(exported_job)" },
   {
    "name": "env",
    "label": "env",
    "query": "label_values({exported_job=\"vm\"},exported_instance)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "<h1>$env<h1>\n\n\n\n" },
  {
   "title": "SP Host CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "vm_cpu_perc{exported_job=\"vm\",core=\"cpu\"}"
    }
   ]
  },
  {
   "title": "SP Host Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "targets": [
    {
     "expr": "vm_mem_perc{exported_job=\"vm\"}"
    }
   ]
  },
  {
   "title": "VMs disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "vm_disk_usage_perc{exported_job=\"vm\"}"
    }
   ]
  },
  {
   "title": "Number of containers",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cnt_created{exported_job=\"containers\"})\n\n"
    }
   ]
  },
  {
   "title": " Licenses acquired number",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " licenses_acquired_number{exported_job=\"SLA\"}\n\n"
    }
   ]
  },
  {
   "title": "Licenses expired number",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "licenses_expired_number{exported_job=\"SLA\"}\n\n"
    }
   ]
  },
  {
   "title": "Licenses utilized number",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "licenses_utilized_number{exported_job=\"SLA\"}\n\n"
    }
   ]
  },
  {
   "title": "Violated agreements ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "percentage_violated_agreements {exported_job=\"SLA\"}"
    }
   ]
  },
  {
   "title": "SP_Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cnt_cpu_perc{exported_job='containers'}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "MEMORY USAGE (%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cnt_mem_perc{exported_job='containers'}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "RX NETWORK TRAFFIC (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "MB/s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cnt_net_rx_MB{exported_job='containers'}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "TX NETWORK TRAFFIC (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "MB/s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cnt_net_tx_MB{exported_job='containers'}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SP_VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "repeat": "VMs",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "vm_cpu_perc{exported_job=\"vm\"}",
       "legendFormat": "{{ core }}"
      }
     ]
    },
    {
     "title": "MEMORY USAGE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "vm_mem_perc{exported_job=\"vm\"}",
       "legendFormat": "{{ exported_instance }}"
      }
     ]
    },
    {
     "title": "DISK USAGE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "vm_disk_usage_perc{exported_job=\"vm\"}",
       "legendFormat": "{{ file_system }}"
      }
     ]
    },
    {
     "title": "RX NETWORK TRAFFIC (bps)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vm_net_rx_bps{exported_job=\"vm\"}",
       "legendFormat": "{{inf}}"
      }
     ]
    },
    {
     "title": "TX NETWORK TRAFFIC (bps)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vm_net_tx_bps{exported_job=\"vm\"}",
       "legendFormat": "{{inf}}"
      }
     ]
    }
   ]
  }
 ]
}