{
 "title": "K8s dashboard",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cnt_name",
    "query": "label_values({name=~\"^k8s.*\",pod=~\"^eu-5gtango.*\"},container)"
   },
   {
    "name": "pod_name",
    "query": "label_values({name=~\"^k8s.*\",pod=~\"^eu-5gtango.*\",container=\"$cnt_name\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container=~\"$cnt_name\"}[1m]))by (pod, container)",
     "legendFormat": "Pod:  {{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container=~\"$cnt_name\",}) by (container, pod)"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"$pod_name\"}[1m]))by (pod, container)",
     "legendFormat": "{{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod=~\"$pod_name\"}) by (pod, container)",
     "legendFormat": "{{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Containers network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$pod_name\"}[1m])) by (container, pod)",
     "legendFormat": "RX pod: {{ pod }} "
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$pod_name\"}[1m])) by (container, pod)",
     "legendFormat": "TX pod: {{ pod }}"
    },
    {
     "expr": "sum (rate (container_network_transmit_errors_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$pod_name\"}[1m])) by (container, pod)",
     "legendFormat": "TX ERRORs pod: {{ pod }}"
    },
    {
     "expr": "sum (rate (container_network_receive_errors_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$pod_name\"}[1m])) by (container, pod)",
     "legendFormat": "RX ERRORs pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "Container fs used bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\",container=~\"$cnt_name\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}